[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winit = "0.26.0"
pixels = "0.10.0"
image = "0.24.9"
shared = { path = "../shared" }

[lib]
path = "src/lib.rs"
